export const FORM_INPUT_SELECTORS = {
    bulkAddLink:"add-bulk-option-link",
    bulkAddTextarea:"bulk-add-options-textarea",
    bulkAddSubmitButton:"bulk-add-options-done-button" ,
    firstName:'input[data-cy="first-name-text-field"]',
    lastName:'input[data-cy="last-name-text-field"]',
    email:'input[data-cy="email-text-field"]',
    multiChoice:'[data-cy="multiple-choice-group"]',
    singleChoice:'.neeto-form-single-choice__item',
    inputTel:'input[type="tel"]',
    formName:'neeto-molecules-value-display',
    saveChanges:'[data-test-id="save-changes-button"]',
    passwordInput:'input[data-cy="password-text-field"]',
    inputOption0:'input-option-0',
    inputOption1:'input-option-1',
    inputOption2:'input-option-2',
    deleteOption2:'delete-option-button-2',
    deleteCheckbox:'delete-archive-alert-archive-checkbox',
    copyLink:'link-copy-button',
    menuList:'menu-list',
    optionSelect:'#react-select-4-option-0'
}